version : '3'
services:
  ekos:
    build: ./php
    image: ekos_php:latest
    container_name: ekos
    hostname: "ekos"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on:
      - db_ekos
  db_ekos:
    image: mariadb:10.2
    container_name: db_ekos
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: djambred
      MYSQL_PASSWORD: p455w0rd1!.
      MYSQL_ROOT_PASSWORD: p455w0rd
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_ekos
  nginx_ekos:
    build: ./nginx
    image: nginx_ekos:latest
    container_name: nginx_ekos
    hostname: "nginx_ekos"
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ekos